# Generated by Django 2.2.6 on 2019-10-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PixApp', '0003_auto_20191023_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
