# Generated by Django 2.2.6 on 2019-10-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PixApp', '0005_auto_20191023_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='favorited_by_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_comments', to='PixApp.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='PixApp.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='favorited_by_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_posts', to='PixApp.User'),
        ),
    ]
